ENH: Add ophyd build for latest release candidate
pcdshub/pcds-recipes pull request #35
Opened 2019-07-29 22:02 UTC by teddyrendahl

2019-07-29 22:07 UTC, ZLLentz approved these changes

2019-08-07 00:02 UTC, klauer requested changes

2019-08-07 00:02 UTC, klauer commented on ophyd/meta.yaml
> +  fn: pydm-{{ version }}.tar.gz
```suggestion
  fn: ophyd-{{ version }}.tar.gz
```

2019-08-07 00:07 UTC, ZLLentz commented on ophyd/meta.yaml
> +  fn: pydm-{{ version }}.tar.gz
Wow, I'm blind. Retracting approval.

2019-08-07 00:08 UTC, ZLLentz requested changes
down with pydm

2019-08-07 15:28 UTC, teddyrendahl commented
And I would have gotten away with it too, if it wasn't for you and your lousy code reviews!

2019-08-07 17:10 UTC, ZLLentz approved these changes

2019-08-14 16:05 UTC, teddyrendahl commented
@klauer Think we need your approval here to merge

2019-08-14 16:06 UTC, klauer approved these changes
Oh... ok!

2019-08-16 00:26 UTC, merged